sudo: required
language: generic

services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)

before_install:
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker build -t levond/react-test --build-arg BUILD_CONTEXT=client .

script:
  - docker run -e CI=true levond/react-test yarn workspace client test

deploy:
  provider: script
  script: bash ./deploy.sh

  on:
    branch: master
