FROM node:lts-alpine as builder
WORKDIR '/base'
COPY package.json yarn.lock .yarnrc.yml ./
COPY .yarn/releases .yarn/releases
COPY .yarn/plugins .yarn/plugins
COPY ./packages/client/package.json packages/client/
RUN yarn install
COPY ./packages/client packages/client
RUN yarn workspace client build

FROM nginx
EXPOSE 3000
COPY ./packages/client/nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /base/packages/client/build /usr/share/nginx/html
